// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Routing is an autogenerated mock type for the Routing type
type Routing struct {
	mock.Mock
}

// InitRouting provides a mock function with no fields
func (_m *Routing) InitRouting() http.Handler {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InitRouting")
	}

	var r0 http.Handler
	if rf, ok := ret.Get(0).(func() http.Handler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}

	return r0
}

// NewRouting creates a new instance of Routing. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRouting(t interface {
	mock.TestingT
	Cleanup(func())
}) *Routing {
	mock := &Routing{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
